<?php

/**
 * @file
 * Contains linkfactory_common.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function linkfactory_common_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the linkfactory_common module.
    case 'help.page.linkfactory_common':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The custom module for test task.') . '</p>';
      return $output;

    default:
  }
}
